# Generated by Django 3.1.7 on 2021-04-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_latestsong_latestvideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LatestSong',
        ),
        migrations.RemoveField(
            model_name='latestvideo',
            name='widget',
        ),
        migrations.AddField(
            model_name='latestvideo',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
